// Generated by gencpp from file takktile_ros/Info.msg
// DO NOT EDIT!


#ifndef TAKKTILE_ROS_MESSAGE_INFO_H
#define TAKKTILE_ROS_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace takktile_ros
{
template <class ContainerAllocator>
struct Info_
{
  typedef Info_<ContainerAllocator> Type;

  Info_()
    : frame_id()
    , xyz()
    , indexes()  {
    }
  Info_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)
    , xyz(_alloc)
    , indexes(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _xyz_type;
  _xyz_type xyz;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _indexes_type;
  _indexes_type indexes;




  typedef boost::shared_ptr< ::takktile_ros::Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::takktile_ros::Info_<ContainerAllocator> const> ConstPtr;

}; // struct Info_

typedef ::takktile_ros::Info_<std::allocator<void> > Info;

typedef boost::shared_ptr< ::takktile_ros::Info > InfoPtr;
typedef boost::shared_ptr< ::takktile_ros::Info const> InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::takktile_ros::Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::takktile_ros::Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace takktile_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'takktile_ros': ['/home/rhr-demo/catkin_ws/src/takktile_ros/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::takktile_ros::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::takktile_ros::Info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::takktile_ros::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::takktile_ros::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::takktile_ros::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::takktile_ros::Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::takktile_ros::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65ae3675ccd5c1fffecb419320f4ac07";
  }

  static const char* value(const ::takktile_ros::Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65ae3675ccd5c1ffULL;
  static const uint64_t static_value2 = 0xfecb419320f4ac07ULL;
};

template<class ContainerAllocator>
struct DataType< ::takktile_ros::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "takktile_ros/Info";
  }

  static const char* value(const ::takktile_ros::Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::takktile_ros::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message format for raw sensor data\n\
string frame_id\n\
geometry_msgs/Point32[] xyz\n\
int32[] indexes\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::takktile_ros::Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::takktile_ros::Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.xyz);
      stream.next(m.indexes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::takktile_ros::Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::takktile_ros::Info_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "xyz[]" << std::endl;
    for (size_t i = 0; i < v.xyz.size(); ++i)
    {
      s << indent << "  xyz[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.xyz[i]);
    }
    s << indent << "indexes[]" << std::endl;
    for (size_t i = 0; i < v.indexes.size(); ++i)
    {
      s << indent << "  indexes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.indexes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAKKTILE_ROS_MESSAGE_INFO_H
