(cl:defpackage reflex_msgs-msg
  (:use )
  (:export
   "<FINGER>"
   "FINGER"
   "<POSECOMMAND>"
   "POSECOMMAND"
   "<HAND>"
   "HAND"
   "<VELOCITYCOMMAND>"
   "VELOCITYCOMMAND"
   "<COMMAND>"
   "COMMAND"
   "<RAWSERVOCOMMANDS>"
   "RAWSERVOCOMMANDS"
   "<MOTOR>"
   "MOTOR"
   "<FORCECOMMAND>"
   "FORCECOMMAND"
   "<FINGERPRESSURE>"
   "FINGERPRESSURE"
   "<RADIANSERVOCOMMANDS>"
   "RADIANSERVOCOMMANDS"
  ))

